### ISSUE TITLE
"Fast Ring" Immediate Monitor notifications (notify first, correct later)

### ISSUE THREAD

**Issue by Defunctionalize** [Great-Hill-Corporation/trueblocks-core#1021]
Fast Ring is the term Windows uses for subscribing to the bleeding edge, possibly unstable OS builds, which is an apt analogy for this feature. Id like to get an initial record from Trueblocks as soon as its detected, with a **flag that indicates it hasn't yet been verified**, so that if it goes unverified for too long, I know that it was from a fork and can clean up.

CURRENT BEHAVIOR
Contract Call is made by user -> TrueBlocks detects this event-> TrueBlocks waits (5) minutes to determine if the information is valid -> Trueblocks publishes this event to subscribers

DESIRED BEHAVIOR
Contract Call is made by user -> TrueBlocks detects this event-> Trueblocks publishes this event to subscribers with `verified: false` ->  TrueBlocks waits (5) minutes to determine if the information is valid -> Trueblocks publishes this event to subscribers again with `verified: true`

**Comment by Mechrophile** [comment]
the verified flag is just a psuedo implementation.  If you have a preferred way to handle that (maybe you verify multiple times and want a way to indicate the degree of confidence or something in a non binary way) then that's totally fine.

I just need some way to tell if some old record turns out to be invalid so I can perform cleanup.

**Comment by tjayrush** [comment]
This is now called 'reading the unripe data'. The idea is in the code, just not documented.
