### ISSUE TITLE
acctScrape may be slower using blooms than not using blooms

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/trueblocks-core#1185]
I'm not sure, but these are a few numbers:

| | 1 account | 10 accounts | 27 accounts |
|----|---|---|----|
| With Blooms | 18.904 secs | 1m 17.901 | 3m 38.052 |
| Without | 21.668 secs | 58.829 | 2m 57.395 |

To reproduce do this:

```
rm -fR $CACHE/monitors
time chifra list --noBlooms <address_list>
time chifra list  <address_list>
```

with different numbers of addresses.

**Comment by naterush** [comment]
Interesting. Some questions:
1. What is acctScrape? Does it just get the list indexes of the transactions, or does it get the indexes and then request the transactions from the node? (I'm guessing the latter, given the rm -rf command).
2. How big are the blooms? 
3. Are these randomly selected accounts? What happens if you do accounts that are in, like, every block? What about accounts that are in like no blocks?
