### ISSUE TITLE
acctExport should use balanceProvider to get balances

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1223]
See below...

**Comment by wildmolasses** [comment]
I hastily titled this issue during our backlog grooming. Now I'm thinking that the title could be revised. It looks like SSH tunnels _will_ be part of our remote rpc endpoint strategy. It's just that the way ssh tunnels are currently used is incorrect. So, let's come up with a different title for this issue -- perhaps "drop extra code and make chifra use default rpc endpoint for balances" 

I intend in trueblocks-docker#185 to give you rpc endpoints on your local machine like localhost:8885 that, despite being "localhost"-addressed, are your remote nodes' rpcs.

**Comment by tjayrush** [comment]
We should talk about this. I think you have a bit of a misunderstanding of the current state of affairs and my needs.

There is already a perfectly working route to get balances if we're local to the archive node. (In other words `chifra export --balances <address>` and curl.... works perfectly on wildmolasses).

The trouble is if I'm running on a different machine than the archive server, and I need balances, I can't get them unless the machine opens it's RPC interface.

I don't think anything more complicated has to happen other than opening the firewall.

There is already a separate 'balanceProvider' config item which I use in the remote case. A perfect example of why we need to separate these RPC's is the case of Infura. In the Infura case, I absolutely do not want to tie every request to a single rpcProvider. I need to separate the balance-related RPC requests from the regular requests, otherwise, the system fails miserably because Infura is slow blindingly slow.

I'm even thinking that we will eventually need a 'traceProvider' config item as well, but that's not been written yet. The same idea would apply there.

Please confirm that you got this message so I know that you're not going down a path that isn't what we need.

**Comment by wildmolasses** [comment]
Instead of opening the firewall (security snafu) there's another solution that's effectively the same without the security problems. We will use persistent ssh tunnels. Trueblocks won't know the difference -- it'll look like another RPC endpoint.

**Comment by tjayrush** [comment]
Will I be able to separate queries for balances (which is the only thing I can't get from a regular tracing node) from all the other queries?

In other words, I want to be able to use a fully local node for everything and only use the remote node for balances. That's already built into my code.

I also want to make sure the user can configure this from the front end (not from a Linux dev-ops perspective). Will that work?

**Comment by wildmolasses** [comment]
> Will I be able to separate queries for balances (which is the only thing I can't get from a regular tracing node) from all the other queries?

You mean use one rpc endpoint for one thing, and a different rpc endpoint for another? Sure.

> In other words, I want to be able to use a fully local node for everything and only use the remote node for balances. That's already built into my code.

I understand you want that option, and you have that option.

> I also want to make sure the user can configure this from the front end (not from a Linux dev-ops perspective). Will that work?

Configure what? The balance provider option? Sure, should be easy. However, I expect that the balance provider's server will have to be configured (from a Linux devops perspective).

**Comment by wildmolasses** [comment]
Hi Jay, I see you assigned this to me. But I think this issue has to deal with removing extra code from trueblocks-core. Is that correct? I'll assign back to you.

**Comment by tjayrush** [comment]
Now that the archive nodes are open to RPC commands (see above), we should remove the very hacky code in `acctExport <address> --balances` to use the `balanceProvider` configuration value. By default `balanceProvider` is the same as `rpcProvider`, but it can be pointed elsewhere. In this case to one of the two archive nodes (`wildmolasses` or `jay-linux`).
