### ISSUE TITLE
when not connected to rpc, chifra status route does not return complete json

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1282]
Steps to reproduce:

1. don't use an active rpc endpoint. (for example, set rpc provider to http://localhost:13696`)
2. Navigate to http://localhost:8080/status?mode_list=monitors&details&ether
3. see that the data returned is incomplete

Filing this issue because I'm maturing the front end codebase. When a request fails, I'd like to provide the user intelligent feedback. Complete json here (including an error message) would help a lot. Should we discuss a general json form?

routes where incomplete json can be found (assuming bad rpc connection):

http://localhost:8080/config?get
http://localhost:8080/status?mode_list=monitors&details&ether

what does done look like?
- all requests return complete json
- most json responses adhere to some canonical shape. deviations should be noted somewhere.

**Comment by tjayrush** [comment]
Got it. Looking into it. I'm quitting early in a wild panic and not finishing sending the JSON. I'll post here and in the discord when it's fixed.

This may happen elsewhere -- which obviously -- points to the need for testing on the API.

**Comment by wildmolasses** [comment]
> points to the need for testing on the API

Here's the issue: [trueblocks-docker#142](https://github.com/Great-Hill-Corporation/trueblocks-docker/issues/142). For the testing part, let's follow up there.

**Comment by tjayrush** [comment]
Different chifra routes either need or do not need a running RPC provider. Since adding `balance` to the monitor status return, `cacheStatus` requires a running node.

To fix this, I removed a line at the start of `cacheStatus` that allowed it to run without a node. You now must have a working RPC to run `chifra status`.

Future improvement (added a new issue in IceBox): allow for running `chifra status` without a node when applicable. (For example, `chifra status --index` should work without a node.)

**Comment by tjayrush** [comment]
I am going to close this specific issue. If it arises again, we can re-open.
