### ISSUE TITLE
QuickBlocks should forward error messages received from Parity node

### ISSUE THREAD

**Issue by paulkuhle** [Great-Hill-Corporation/trueblocks-core#635]
It would be helpful to have QuickBlocks forward error messages received from the Parity node instead of printing out generic ones. This would make it easier to troubleshoot problems.

In our case, the host header whitelist in our Parity configuration file was incorrectly set up after upgrading Parity. Applications like getBlock would return *The last valid block is 0.*, whereas the actual Parity error *Provided host header is not whitelisted* would have been more helpful.

**Comment by tjayrush** [comment]
Documenting what happened here.

User upgraded Parity against a working version of their code and all of a sudden QuickBlocks started reporting an invalid block number (last valid block is zero, implies the block number they tried to request was higher).

An easy way to tell what's going on in a situation such as this is to eliminate QuickBlocks from the situation entirely. On this page (https://wiki.parity.io/JSONRPC) is `Parity's` RPC specification (there's n similar spec for `geth`) which describes how one may interact with the node directly. Three-quarters of the way down that page is a link to the [eth module](https://wiki.parity.io/JSONRPC-eth-module.html), and on that page is a spec for `eth_getBlockByNumber`.  In this section is the following `curl` code which I instructed the user to copy and paste into the command line:

    curl --data '{"method":"eth_getBlockByNumber","params":["0x1b4",true],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545

This interacts directly with Parity, eliminating QuickBlocks from the situation. This returned `Provided host header is not whitelisted` which QuickBlocks was naively interpreting as JSON, which wouldn't parse, which is why it was reporting invalid blocks numbers.

The suggestion is to do more error reporting. This will be fixed before the next release.

**Comment by tjayrush** [comment]
This is now exposed through the logging feature.
