### ISSUE TITLE
scraper.py: no timeout if chain not synced

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#989]

**Comment by tjayrush** [comment]
Scraper will simply go to sleep and come alive and scrape whatever's available since the last time it ran. It follows the chain. If the chain stalls (i.e. I unplug my machine from the internet), scraper blindly waits (coming alive every X seconds) until more data becomes available. I would argue this is exactly how it should work. It should never time out. If Parity dies, it should die, but it shouldn't time out as long as parity is alive.

**Comment by tjayrush** [comment]
Can you please be more specific here? Is this in reference to #1012?

**Comment by tjayrush** [comment]
Scraper.py is long since gone. This is working as designed.
